config/routes.rb
Rails.application.routes.draw do
  get 'favorites/index'
  root 'sessions#new'
  get 'posts/index'
  resources :posts do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:index, :create, :destroy, :show]

  mount LetterOpenerWeb::Engine, at: "/inbox"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: {maximum: 255}
  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, :username, length: {in: 1..25}
    before_validation {name.capitalize!}
    before_validation {username.downcase!}
    validates :email, presence: true, length: {maximum: 255}, uniqueness: true, 
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation {email.downcase!}
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    has_many :posts
    mount_uploader :photo, PhotoUploader
    has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    
    before_action :login_required

    private
    def login_required
        redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: params[:id])
  end

  def create
      current_user.favorites.create(post_id: params[:post_id])
      flash[:info] = "Ce post a été ajouté à vos favoris"
      redirect_to posts_path
  end

  def destroy
    current_user.favorites.find_by(id: params[:id]).destroy
    flash[:danger] = "Ce post a été retiré de vos favoris"
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :get_all_post, only: %i[ index create confirm ]
  before_action :save_post, only: %i[ create confirm ]

  def index
    @post = Post.new
  end

  def show
  end

  def edit
  end

  def update
    if params[:Back]
      redirect_to user_path(current_user)
    else
      if @post.update(post_params)
        flash[:info] = "Publication modifiée avec succès !!!"
        redirect_to user_path(current_user)
      else
        render "edit"
      end
    end
  end

  def destroy
    @post.destroy
    flash[:danger] = "Publication supprimée !!!"
    redirect_to user_path(current_user.id)
  end

  def confirm
    render "posts/index" if @post.invalid?
  end

  def create
    
    if params[:Back]
      render "index"
    else
      if @post.save
        PostMailer.with(user: current_user).post_created.deliver_now
        redirect_to posts_path
        flash[:success] = "Publication enrégistrée !!!"
      else
        render :index
      end
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def get_all_post
    @posts = Post.all.order(created_at: :desc)
  end

  def post_params
    params.require(:post).permit(:photo, :photo_cache, :content)
  end

  def save_post
    @post = current_user.posts.build(post_params)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    redirect_to user_path(current_user) if current_user
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] = "Déconnecté"
    redirect_to new_session_path
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "Echec connexion. E-mail ou mot de passe incorrect"
      render "sessions/new"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    @user = User.new
    redirect_to user_path(current_user) if current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def confirm
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:info] = "Profil modifié avec succès !!!"
      redirect_to user_path(current_user)
    else
      render "edit"
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites = current_user.favorites
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to new_session_path
        flash[:success] = "Compte créé avec succès. Veuillez vous connecter"
    else
        render :new
    end
  end

  private
  def user_params
      params.require(:user).permit(:name, :username, :email, :password,:photo, :photo_cache)
  end

  def user_params_without_pwd
    params.require(:user).permit(:name, :username, :email,:photo, :photo_cache)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def choose_new_or_edit
        if action_name == 'index' || action_name == 'create'
          confirm_posts_path
        elsif action_name == 'edit'
          post_path
        end
    end

    def get_current_user_post
      @posts = Post.where(user_id: current_user.id).order(updated_at: :desc)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        current_user.present?
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<%= render "partials/header" %>

<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <h3>MES FAVORIS</h3>
        </div>
        <div class="panel second-line">
            <div class="panel-body" style="padding: 0;margin: 0;">
                <% @favorites.each do |favorite| %>
                <div class="col-sm-3" style="border:1px solid lightgray;height:100px; overflow:hidden">
                    <td><a title="Afficher" href="/favorites/<%= favorite.post.id %>"><%= image_tag favorite.post.photo.url, width: "100%" %></a></td>
                </div>
                <% end %>
            </div>
        </div>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>

app/views/favorites/show.html.erb
<%= render "partials/header" %>

<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <h3>DETAILS DU FAVORIS</h3>
        </div>
        <div class="panel second-line">
            <div class="panel-heading" style="display:flex;justify-content:space-between">
                <table class="profil-table">
                    <tr>
                        <td>
                            <div class="profil-pic">
                                <% if @favorite.post.user.photo.url %>
                                <%= image_tag @favorite.post.user.photo.url, width: "100%" %>
                                <% else %>
                                <%= image_tag "/images/user_insta.png", width: "100%" %>
                                <% end %>
                            </div>  
                        </td>
                        <td>
                            <h3 class="panel-title"><strong><%= @favorite.post.user.username %></strong></h3>
                        </td>
                    </tr>
                </table>
                <div class="btn-group" role="group" aria-label="...">
                    <%= link_to 'Back', favorites_path, class: "btn btn-default btn-sm" %>
                </div>
            </div>
            <div class="panel-body" style="padding: 0;margin: 0;">
                <%= image_tag @favorite.post.photo.url, width: "100%", alt: "" if @favorite.post.photo %>            
            </div>
            <div class="panel-heading" style="border: 0;">
                <table>
                    <tr>
                        <td>
                            <button class="btn btn-default" type="button">
                                Like <span class="badge"><%= @favorite.post.favorites.count %></span>
                            </button>
                        </td>
                    </tr>
                    <tr >
                        <td>
                            <blockquote class="text-justify" style="margin-top: 5px;">
                                 <%= @favorite.post.content %>
                            </blockquote>
                        </td>
                    </tr>
                    <tr>
                        <td style="color: rgb(192, 192, 192);">
                            <em>Posté le <%= @favorite.post.created_at.to_s.to_time.strftime('%e-%m-%Y à %k:%M') %></em>
                        </td>
                    </tr>
                    <tr>
                        <td style="color: rgb(192, 192, 192);">
                            <em>Mis à jour le <%= @favorite.post.updated_at.to_s.to_time.strftime('%e-%m-%Y à %k:%M') %></em>
                        </td>
                    </tr>
                </table>    
            </div>
        </div>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram Clone</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <link rel="icon" type="images/png" href="/images/autocollants-logo-instagram.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_errors-post.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    <p><%= notice %></p>
    <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_errors.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <p><%= notice %></p>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key} text-center") %>
<% end %>

app/views/partials/_footer.html.erb
<footer class="bg-light text-center text-lg-start navbar-fixed-bottom">
    <!-- Copyright -->
    <div class="text-center p-3">
        COPYRIGHT &COPY Août 2021, ALL RIGHTS RESERVED, Designed By Chaldrak
    </div>
    <!-- Copyright -->
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/posts/index">
            <img src="/images/1024px-Instagram_logo.svg.png" alt="" width="100px">
        </a>
        </div>
        
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/posts/index">
                <svg aria-label="Accueil" class="_8-yf5 " fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22">
                    <path d="M45.5 48H30.1c-.8 0-1.5-.7-1.5-1.5V34.2c0-2.6-2.1-4.6-4.6-4.6s-4.6 2.1-4.6 4.6v12.3c0 .8-.7 1.5-1.5 1.5H2.5c-.8 0-1.5-.7-1.5-1.5V23c0-.4.2-.8.4-1.1L22.9.4c.6-.6 1.6-.6 2.1 0l21.5 21.5c.3.3.4.7.4 1.1v23.5c.1.8-.6 1.5-1.4 1.5z">
                    </path>
                </svg>
                </a>
            </li>
            <li>
                <a href="#">
                    <svg aria-label="Messenger" class="_8-yf5 " fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M36.2 16.7L29 22.2c-.5.4-1.2.4-1.7 0l-5.4-4c-1.6-1.2-3.9-.8-5 .9l-6.8 10.7c-.7 1 .6 2.2 1.6 1.5l7.3-5.5c.5-.4 1.2-.4 1.7 0l5.4 4c1.6 1.2 3.9.8 5-.9l6.8-10.7c.6-1.1-.7-2.2-1.7-1.5zM24 1C11 1 1 10.5 1 23.3 1 30 3.7 35.8 8.2 39.8c.4.3.6.8.6 1.3l.2 4.1c0 1 .9 1.8 1.8 1.8.2 0 .5 0 .7-.2l4.6-2c.2-.1.5-.2.7-.2.2 0 .3 0 .5.1 2.1.6 4.3.9 6.7.9 13 0 23-9.5 23-22.3S37 1 24 1zm0 41.6c-2 0-4-.3-5.9-.8-.4-.1-.8-.2-1.3-.2-.7 0-1.3.1-2 .4l-3 1.3V41c0-1.3-.6-2.5-1.6-3.4C6.2 34 4 28.9 4 23.3 4 12.3 12.6 4 24 4s20 8.3 20 19.3-8.6 19.3-20 19.3z"></path></svg>
                </a>
            </li>
            <li>
                <a href="#">
                    <svg aria-label="Trouver des personnes" class="_8-yf5 " fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path clip-rule="evenodd" d="M24 0C10.8 0 0 10.8 0 24s10.8 24 24 24 24-10.8 24-24S37.2 0 24 0zm0 45C12.4 45 3 35.6 3 24S12.4 3 24 3s21 9.4 21 21-9.4 21-21 21zm10.2-33.2l-14.8 7c-.3.1-.6.4-.7.7l-7 14.8c-.3.6-.2 1.3.3 1.7.3.3.7.4 1.1.4.2 0 .4 0 .6-.1l14.8-7c.3-.1.6-.4.7-.7l7-14.8c.3-.6.2-1.3-.3-1.7-.4-.5-1.1-.6-1.7-.3zm-7.4 15l-5.5-5.5 10.5-5-5 10.5z" fill-rule="evenodd"></path></svg>
                </a>
            </li>
            <li>
                <a href="#">
                    <svg aria-label="Fil d’activité" class="_8-yf5 " fill="#262626" height="22" role="img" viewBox="0 0 48 48" width="22"><path d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z"></path></svg>
                </a>
            </li>
            <li>
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                    <div class="profil-pic-small">
                        <% if current_user.photo.url %>
                        <%= image_tag current_user.photo.url, width: "100%" %>
                        <% else %>
                        <%= image_tag "/images/user_insta.png", width: "100%" %>
                        <% end %>
                    </div>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="/users/<%= current_user.id %>">
                            <svg aria-label="Profil" class="_8-yf5 " fill="#262626" height="16" role="img" viewBox="0 0 32 32" width="16"><path d="M16 0C7.2 0 0 7.1 0 16c0 4.8 2.1 9.1 5.5 12l.3.3C8.5 30.6 12.1 32 16 32s7.5-1.4 10.2-3.7l.3-.3c3.4-3 5.5-7.2 5.5-12 0-8.9-7.2-16-16-16zm0 29c-2.8 0-5.3-.9-7.5-2.4.5-.9.9-1.3 1.4-1.8.7-.5 1.5-.8 2.4-.8h7.2c.9 0 1.7.3 2.4.8.5.4.9.8 1.4 1.8-2 1.5-4.5 2.4-7.3 2.4zm9.7-4.4c-.5-.9-1.1-1.5-1.9-2.1-1.2-.9-2.7-1.4-4.2-1.4h-7.2c-1.5 0-3 .5-4.2 1.4-.8.6-1.4 1.2-1.9 2.1C4.2 22.3 3 19.3 3 16 3 8.8 8.8 3 16 3s13 5.8 13 13c0 3.3-1.2 6.3-3.3 8.6zM16 5.7c-3.9 0-7 3.1-7 7s3.1 7 7 7 7-3.1 7-7-3.1-7-7-7zm0 11c-2.2 0-4-1.8-4-4s1.8-4 4-4 4 1.8 4 4-1.8 4-4 4z"></path></svg>
                            <span> Profil</span>
                        </a>
                    </li>
                    <li>
                        <a href="/favorites/index">
                            <svg aria-label="Favoris" class="_8-yf5 " fill="#262626" height="16" role="img" viewBox="0 0 32 32" width="16"><path d="M28.7 32c-.4 0-.8-.2-1.1-.4L16 19.9 4.4 31.6c-.4.4-1.1.6-1.6.3-.6-.2-.9-.8-.9-1.4v-29C1.8.7 2.5 0 3.3 0h25.4c.8 0 1.5.7 1.5 1.5v29c0 .6-.4 1.2-.9 1.4-.2.1-.4.1-.6.1zM4.8 3v23.9l9.4-9.4c.9-.9 2.6-.9 3.5 0l9.4 9.4V3H4.8z"></path></svg>
                            <span> Favoris</span>
                        </a>
                    </li>
                    <li role="separator" class="divider"></li>
                    <li><%= link_to "Déconnexion", session_path(current_user.id), method: :delete, data: { confirm: 'Au revoir et à la prochaine !!!' } %></li>
                </ul>
            </li>
        </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

app/views/posts/confirm.html.erb
<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <h3>CONFIRMATION DE PUBLICATION</h3>
        </div>
        <div class="panel second-line">
            <div class="panel-body" style="padding: 0;margin: 0;">
                <%= image_tag @post.photo.url, width: 200 %>
            </div>
            
            <div class="panel-heading" style="border: 0;">
                <table>
                    <tr >
                        <td>
                            <blockquote class="text-justify" style="margin-top: 5px;">
                                <%= @post.content %>
                            </blockquote>
                        </td>
                    </tr>
                </table>
                <div>
                    <%= form_with(model: @post, local: true) do |form| %>
                        <%= form.hidden_field :content %>
                        <%= form.hidden_field :photo_cache %>
                        <%= form.submit "Valider", class: "btn btn-info"%>
                        <%= form.submit "Annuler", name:"Back", class: "btn btn-default"%>
                    <% end %>
                </div>
            </div>
        </div>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>

app/views/posts/edit.html.erb
<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <h3>MODIFICATION DE PUBLICATION</h3>
        </div>
        <div class="panel second-line">
            
            <div class="panel-heading" style="border: 0;">
                <%= form_with(model: @post, local: true, class: "form-horizontal", url: choose_new_or_edit) do |form| %>
                    <%= render "partials/errors-post" %>
                    <div class="form-group">
                        <%= form.label :Message, class: "col-sm-2 control-label"%>
                        <div class="col-sm-10">
                        <%= form.text_area :content, class:"form-control"%>
                        </div>
                    </div>
                    <div class="form-group">
                        <%= form.label :Photo, class: "col-sm-2 control-label"%>
                        <div class="col-sm-10">
                        <%= form.file_field :photo, class: "form-control" %>
                        <%= form.hidden_field :photo_cache %>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                        <%= form.submit "Enrégistrer", class: "btn btn-info"%>
                        <%= form.submit "Annuler", name: "Back", class: "btn btn-default" %>
                        </div>
                    </div>
                <% end %>  
            </div>
        </div>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>

app/views/posts/show.html.erb
<%= render "partials/header" %>

<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <h3>DETAILS PUBLICATION</h3>
        </div>
        <div class="panel second-line">
            <div class="panel-heading" style="display:flex;justify-content:space-between">
                <table class="profil-table">
                    <tr>
                        <td>
                            <div class="profil-pic">
                                <% if current_user.photo.url %>
                                <%= image_tag current_user.photo.url, width: "100%" %>
                                <% else %>
                                <%= image_tag "/images/user_insta.png", width: "100%" %>
                                <% end %>
                            </div>  
                        </td>
                        <td>
                            <h3 class="panel-title"><strong><%= @post.user.username %></strong></h3>
                        </td>
                    </tr>
                </table>
                <div class="btn-group" role="group" aria-label="...">
                    <%= link_to 'Back', user_path(current_user), class: "btn btn-default btn-sm" %>
					<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info btn-sm" %>
                </div>
            </div>
            <div class="panel-body" style="padding: 0;margin: 0;">
                <%= image_tag @post.photo.url, width: "100%", alt: "" if @post.photo %>            
            </div>
            <div class="panel-heading" style="border: 0;">
                <table>
                    <tr>
                        <td>
                            <button class="btn btn-default" type="button">
                                Like <span class="badge">4</span>
                            </button>
                        </td>
                    </tr>
                    <tr >
                        <td>
                            <blockquote class="text-justify" style="margin-top: 5px;">
                                 <%= @post.content %>
                            </blockquote>
                        </td>
                    </tr>
                    <tr>
                        <td style="color: rgb(192, 192, 192);">
                            <em>Posté le <%= @post.created_at.to_s.to_time.strftime('%e-%m-%Y à %k:%M') %></em>
                        </td>
                    </tr>
                    <tr>
                        <td style="color: rgb(192, 192, 192);">
                            <em>Mis à jour le <%= @post.updated_at.to_s.to_time.strftime('%e-%m-%Y à %k:%M') %></em>
                        </td>
                    </tr>
                </table>    
            </div>
        </div>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>

app/views/users/show.html.erb
<%= render "partials/header" %>

<div class="index-all">
    <div class="container page">
        <div class="row first-line-profile">
            <div class="col-sm-4">
                <div class="profil-pic-big">
                    <% if current_user.photo.url %>
                    <%= image_tag current_user.photo.url, width: "100%"%>
                    <% else %>
                    <%= image_tag "/images/user_insta.png", width: "100%" %>
                    <% end %>
                </div>
            </div>
            <div class="col-sm-8">
                <div>
                    <div>
                        <table>
                            <tr>
                                <td>
                                    <h2><%= current_user.username %></h2>
                                </td>
                                <td>
                                    <%= link_to "Modifier profil", edit_user_path(current_user), class: "btn btn-default btn-sm"%>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div>
                        <table>
                            <tr>
                                <td>
                                    <p><strong><%= get_current_user_post.count %></strong> <%= pluralize(get_current_user_post.count, 'Publication', 'Publications').split(' ')[1] %></p>
                                </td>
                                <td>
                                    <p><strong><%= @favorites.count %></strong> favoris</p>
                                </td>
                                <td>
                                    <p><strong>0</strong> abonnements</p>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <h4><strong><%= current_user.name %></strong></h4>
                </div>
            </div>
        </div>
        <%= render "partials/flash" %>
        <% if get_current_user_post.size == 0 %>
        <div class="alert alert-warning text-center">
            <p>Aucune publication trouvée...</p>
        </div>
        <% end %>
        <% get_current_user_post.each do |post| %>
        <div class="row second-line-profile">
            <div class="col-xs-12 panel">
                <div class="panel-heading" style="display:flex;justify-content:space-between">
                    <div>
                        <strong style="color: rgb(163, 10, 10);font-size: 2rem;"><%= post.favorites.count %> <span class="glyphicon glyphicon-heart"></span></strong>
                    </div>
                    <div class="btn-group" role="group" aria-label="...">
                        <%= link_to 'Show', post, class: "btn btn-default btn-sm" %>
						<%= link_to 'Edit', edit_post_path(post), class: "btn btn-info btn-sm" %>
						<%= link_to 'Delete', post, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Vous êtes sûr de vouloir supprimer cette publication ?' } %>
                    </div>
                </div>
                <div class="panel-body" style="padding: 0;margin: 0;">
                    <%= image_tag post.photo.url, width: "100%", alt: "" if post.photo %>
                </div>
            </div>
        </div>
        <% end %>

        <div class="row text-justify" style="margin: 0px 0 50px 0;"></div>
    </div>

    <%= render "partials/footer" %>

</div>